In [102]:
#hi
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [103]:
df1 = pd.read_excel('/content/Lab Session Data.xlsx', sheet_name="Purchase data")
df2 = pd.read_excel('/content/Lab Session Data.xlsx', sheet_name="IRCTC Stock Price")
df3 = pd.read_excel('/content/Lab Session Data.xlsx', sheet_name="thyroid0387_UCI")
df4 =  pd.read_excel('/content/Lab Session Data.xlsx', sheet_name="marketing_campaign")

In [104]:
df2.head()

Date Month  Day    Price     Open     High      Low   Volume  \
0  Jun 29, 2021   Jun  Tue  2081.85  2092.00  2126.90  2065.05    1.67M   
1  Jun 28, 2021   Jun  Mon  2077.75  2084.00  2112.45  2068.40  707.73K   
2  Jun 25, 2021   Jun  Fri  2068.85  2084.35  2088.50  2053.10  475.82K   
3  Jun 24, 2021   Jun  Thu  2072.95  2098.00  2098.00  2066.00  541.51K   
4  Jun 23, 2021   Jun  Wed  2078.25  2102.00  2111.40  2072.00  809.62K   

     Chg%  
0  0.0020  
1  0.0043  
2 -0.0020  
3 -0.0026  
4 -0.0023

In [105]:
df3.head()

Record ID  age sex on thyroxine query on thyroxine  \
0  840801013   29   F            f                  f   
1  840801014   29   F            f                  f   
2  840801042   41   F            f                  f   
3  840803046   36   F            f                  f   
4  840803047   32   F            f                  f   

  on antithyroid medication sick pregnant thyroid surgery I131 treatment  ...  \
0                         f    f        f               f              f  ...   
1                         f    f        f               f              f  ...   
2                         f    f        f               f              f  ...   
3                         f    f        f               f              f  ...   
4                         f    f        f               f              f  ...   

  TT4 measured  TT4 T4U measured T4U FTI measured FTI TBG measured TBG  \
0            f    ?            f   ?            f   ?            f   ?   
1            t  128            f   ?            f   ?            f   ?   
2            f    ?            f   ?            f   ?            t  11   
3            f    ?            f   ?            f   ?            t  26   
4            f    ?            f   ?            f   ?            t  36   

  referral source     Condition  
0           other  NO CONDITION  
1           other  NO CONDITION  
2           other  NO CONDITION  
3           other  NO CONDITION  
4           other             S  

[5 rows x 31 columns]

In [106]:
df4.head()

ID  Year_Birth   Education Marital_Status   Income  Kidhome  Teenhome  \
0  5524        1957  Graduation         Single  58138.0        0         0   
1  2174        1954  Graduation         Single  46344.0        1         1   
2  4141        1965  Graduation       Together  71613.0        0         0   
3  6182        1984  Graduation       Together  26646.0        1         0   
4  5324        1981         PhD        Married  58293.0        1         0   

           Dt_Customer  Recency  MntWines  ...  NumWebVisitsMonth  \
0  2012-04-09 00:00:00       58       635  ...                  7   
1  2014-08-03 00:00:00       38        11  ...                  5   
2           21-08-2013       26       426  ...                  4   
3  2014-10-02 00:00:00       26        11  ...                  6   
4           19-01-2014       94       173  ...                  5   

   AcceptedCmp3  AcceptedCmp4  AcceptedCmp5  AcceptedCmp1  AcceptedCmp2  \
0             0             0             0             0             0   
1             0             0             0             0             0   
2             0             0             0             0             0   
3             0             0             0             0             0   
4             0             0             0             0             0   

   Complain  Z_CostContact  Z_Revenue  Response  
0         0              3         11         1  
1         0              3         11         0  
2         0              3         11         0  
3         0              3         11         0  
4         0              3         11         0  

[5 rows x 29 columns]

In [107]:
df1.head()

Customer  Candies (#)  Mangoes (Kg)  Milk Packets (#)  Payment (Rs)  \
0      C_1           20             6                 2           386   
1      C_2           16             3                 6           289   
2      C_3           27             6                 2           393   
3      C_4           19             1                 2           110   
4      C_5           24             4                 2           280   

   Unnamed: 5  Unnamed: 6  Unnamed: 7  Unnamed: 8  Unnamed: 9  ...  \
0         NaN         NaN         NaN         NaN         NaN  ...   
1         NaN         NaN         NaN         NaN         NaN  ...   
2         NaN         NaN         NaN         NaN         NaN  ...   
3         NaN         NaN         NaN         NaN         NaN  ...   
4         NaN         NaN         NaN         NaN         NaN  ...   

   Unnamed: 12  Unnamed: 13  Unnamed: 14  Unnamed: 15  Unnamed: 16  \
0          NaN          NaN          NaN          NaN          NaN   
1          NaN          NaN          NaN          NaN          NaN   
2          NaN          NaN          NaN          NaN          NaN   
3          NaN          NaN          NaN          NaN          NaN   
4          NaN          NaN          NaN          NaN          NaN   

   Unnamed: 17  Unnamed: 18  Candy  Mango  Milk  
0          NaN          NaN    1.0   55.0  18.0  
1          NaN          NaN    NaN    NaN   NaN  
2          NaN          NaN    NaN    NaN   NaN  
3          NaN          NaN    NaN    NaN   NaN  
4          NaN          NaN    NaN    NaN   NaN  

[5 rows x 22 columns]

In [108]:
from collections.abc import ValuesView
Z = df1.iloc[:,:5].values
C = df1.iloc[:,4:5].values
C
A = df1.iloc[:,1:4].values
A

array([[20,  6,  2],
       [16,  3,  6],
       [27,  6,  2],
       [19,  1,  2],
       [24,  4,  2],
       [22,  1,  5],
       [15,  4,  2],
       [18,  4,  2],
       [21,  1,  4],
       [16,  2,  4]])

In [109]:
PO = np.linalg.pinv(A)
PO

array([[-0.01008596, -0.03124505,  0.01013951,  0.0290728 ,  0.0182907 ,
         0.01161794, -0.00771348,  0.00095458,  0.01743623, -0.00542016],
       [ 0.09059668,  0.07263726,  0.03172933, -0.09071908, -0.01893196,
        -0.06926996,  0.05675464,  0.03152577, -0.07641966,  0.00357352],
       [ 0.00299878,  0.15874243, -0.05795468, -0.06609024, -0.06295043,
         0.03348017,  0.01541831, -0.01070461,  0.00029003,  0.05938755]])

In [110]:
X = np.dot(PO,C)
X

array([[ 1.],
       [55.],
       [18.]])

In [111]:
df1

Customer  Candies (#)  Mangoes (Kg)  Milk Packets (#)  Payment (Rs)  \
0      C_1           20             6                 2           386   
1      C_2           16             3                 6           289   
2      C_3           27             6                 2           393   
3      C_4           19             1                 2           110   
4      C_5           24             4                 2           280   
5      C_6           22             1                 5           167   
6      C_7           15             4                 2           271   
7      C_8           18             4                 2           274   
8      C_9           21             1                 4           148   
9     C_10           16             2                 4           198   

   Unnamed: 5  Unnamed: 6  Unnamed: 7  Unnamed: 8  Unnamed: 9  ...  \
0         NaN         NaN         NaN         NaN         NaN  ...   
1         NaN         NaN         NaN         NaN         NaN  ...   
2         NaN         NaN         NaN         NaN         NaN  ...   
3         NaN         NaN         NaN         NaN         NaN  ...   
4         NaN         NaN         NaN         NaN         NaN  ...   
5         NaN         NaN         NaN         NaN         NaN  ...   
6         NaN         NaN         NaN         NaN         NaN  ...   
7         NaN         NaN         NaN         NaN         NaN  ...   
8         NaN         NaN         NaN         NaN         NaN  ...   
9         NaN         NaN         NaN         NaN         NaN  ...   

   Unnamed: 12  Unnamed: 13  Unnamed: 14  Unnamed: 15  Unnamed: 16  \
0          NaN          NaN          NaN          NaN          NaN   
1          NaN          NaN          NaN          NaN          NaN   
2          NaN          NaN          NaN          NaN          NaN   
3          NaN          NaN          NaN          NaN          NaN   
4          NaN          NaN          NaN          NaN          NaN   
5          NaN          NaN          NaN          NaN          NaN   
6          NaN          NaN          NaN          NaN          NaN   
7          NaN          NaN          NaN          NaN          NaN   
8          NaN          NaN          NaN          NaN          NaN   
9          NaN          NaN          NaN          NaN          NaN   

   Unnamed: 17  Unnamed: 18  Candy  Mango  Milk  
0          NaN          NaN    1.0   55.0  18.0  
1          NaN          NaN    NaN    NaN   NaN  
2          NaN          NaN    NaN    NaN   NaN  
3          NaN          NaN    NaN    NaN   NaN  
4          NaN          NaN    NaN    NaN   NaN  
5          NaN          NaN    NaN    NaN   NaN  
6          NaN          NaN    NaN    NaN   NaN  
7          NaN          NaN    NaN    NaN   NaN  
8          NaN          NaN    NaN    NaN   NaN  
9          NaN          NaN    NaN    NaN   NaN  

[10 rows x 22 columns]

In [112]:
Purchase_data = pd.DataFrame(A)
Purchase_data['Billing'] = C
Status = []
for i in Purchase_data['Billing']:
      if i>200:
        Status.append("Rich")
      else:
        Status.append("Poor")
Purchase_data['Status'] = Status


Purchase_data


0  1  2  Billing Status
0  20  6  2      386   Rich
1  16  3  6      289   Rich
2  27  6  2      393   Rich
3  19  1  2      110   Poor
4  24  4  2      280   Rich
5  22  1  5      167   Poor
6  15  4  2      271   Rich
7  18  4  2      274   Rich
8  21  1  4      148   Poor
9  16  2  4      198   Poor

In [113]:
df2

Date Month  Day    Price     Open     High      Low   Volume  \
0    Jun 29, 2021   Jun  Tue  2081.85  2092.00  2126.90  2065.05    1.67M   
1    Jun 28, 2021   Jun  Mon  2077.75  2084.00  2112.45  2068.40  707.73K   
2    Jun 25, 2021   Jun  Fri  2068.85  2084.35  2088.50  2053.10  475.82K   
3    Jun 24, 2021   Jun  Thu  2072.95  2098.00  2098.00  2066.00  541.51K   
4    Jun 23, 2021   Jun  Wed  2078.25  2102.00  2111.40  2072.00  809.62K   
..            ...   ...  ...      ...      ...      ...      ...      ...   
244  Jul 07, 2020   Jul  Tue  1397.40  1410.00  1411.00  1390.05  480.21K   
245  Jul 06, 2020   Jul  Mon  1400.75  1405.50  1415.50  1394.00  614.93K   
246  Jul 03, 2020   Jul  Fri  1405.10  1415.00  1425.00  1398.00  599.49K   
247  Jul 02, 2020   Jul  Thu  1412.35  1440.00  1467.80  1395.30    2.16M   
248  Jul 01, 2020   Jul  Wed  1363.05  1363.65  1377.00  1356.00  383.00K   

       Chg%  
0    0.0020  
1    0.0043  
2   -0.0020  
3   -0.0026  
4   -0.0023  
..      ...  
244 -0.0024  
245 -0.0031  
246 -0.0051  
247  0.0362  
248  0.0032  

[249 rows x 9 columns]

In [114]:
Mean_Price = df2["Price"].mean()
Median = df2["Price"].median()
Mode = df2["Price"].mode()
Variance = df2["Price"].var()
print(Variance)
print(Mean_Price)

58732.36535253918
1560.6634538152612


In [117]:
A = []
mean_of_wednesday = 0
filtered_df = df2[df2["Day"] == "Wed"]
if not filtered_df.empty:
  A.append(filtered_df["Price"])

A
ZZZ=pd.DataFrame(A)

In [118]:
ZZZ

4        9       14       19       24      29      33       38   \
Price  2078.25  2089.95  2071.2  1917.95  1894.05  1858.1  1746.6  1723.65   

           43      56   ...      203     208     213     218      223  \
Price  1795.85  1709.0  ...  1359.75  1369.3  1361.8  1386.8  1336.95   

           228      233      238     243      248  
Price  1352.75  1372.95  1351.95  1390.1  1363.05  

[1 rows x 50 columns]

In [122]:
sum= 0
for i in ZZZ:
  sum = sum+i
print(sum/50)

127.62
